# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reussi.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WorkShop(object):
    def setupUi(self, WorkShop):
        WorkShop.setObjectName("WorkShop")
        WorkShop.resize(383, 648)
        WorkShop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.centralwidget = QtWidgets.QWidget(WorkShop)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_Logo = QtWidgets.QLabel(self.centralwidget)
        self.label_Logo.setText("")
        self.label_Logo.setPixmap(QtGui.QPixmap("../WorkShop\'s Plan/images/lagrace.png"))
        self.label_Logo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Logo.setObjectName("label_Logo")
        self.gridLayout_5.addWidget(self.label_Logo, 0, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Nom = QtWidgets.QLabel(self.groupBox)
        self.label_Nom.setObjectName("label_Nom")
        self.gridLayout.addWidget(self.label_Nom, 0, 0, 1, 1)
        self.lineEdit_Nom = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Nom.setObjectName("lineEdit_Nom")
        self.gridLayout.addWidget(self.lineEdit_Nom, 0, 1, 1, 1)
        self.label_Prenom = QtWidgets.QLabel(self.groupBox)
        self.label_Prenom.setObjectName("label_Prenom")
        self.gridLayout.addWidget(self.label_Prenom, 1, 0, 1, 1)
        self.lineEdit_Prenom = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Prenom.setObjectName("lineEdit_Prenom")
        self.gridLayout.addWidget(self.lineEdit_Prenom, 1, 1, 1, 1)
        self.label_Sexe = QtWidgets.QLabel(self.groupBox)
        self.label_Sexe.setObjectName("label_Sexe")
        self.gridLayout.addWidget(self.label_Sexe, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_Masculin = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Masculin.setObjectName("radioButton_Masculin")
        self.horizontalLayout_2.addWidget(self.radioButton_Masculin)
        self.radioButton_Feminin = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_Feminin.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.Chad))
        self.radioButton_Feminin.setChecked(True)
        self.radioButton_Feminin.setAutoRepeat(False)
        self.radioButton_Feminin.setObjectName("radioButton_Feminin")
        self.horizontalLayout_2.addWidget(self.radioButton_Feminin)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 1, 1, 1)
        self.label_Quartier = QtWidgets.QLabel(self.groupBox)
        self.label_Quartier.setObjectName("label_Quartier")
        self.gridLayout.addWidget(self.label_Quartier, 3, 0, 1, 1)
        self.lineEdit_Quartier = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Quartier.setObjectName("lineEdit_Quartier")
        self.gridLayout.addWidget(self.lineEdit_Quartier, 3, 1, 1, 1)
        self.label_Telephone = QtWidgets.QLabel(self.groupBox)
        self.label_Telephone.setObjectName("label_Telephone")
        self.gridLayout.addWidget(self.label_Telephone, 4, 0, 1, 1)
        self.lineEdit_Telephone = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Telephone.setObjectName("lineEdit_Telephone")
        self.gridLayout.addWidget(self.lineEdit_Telephone, 4, 1, 1, 1)
        self.label_Email = QtWidgets.QLabel(self.groupBox)
        self.label_Email.setObjectName("label_Email")
        self.gridLayout.addWidget(self.label_Email, 5, 0, 1, 1)
        self.lineEdit_Email = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.gridLayout.addWidget(self.lineEdit_Email, 5, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 1, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.comboBox_Modele = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_Modele.setObjectName("comboBox_Modele")
        self.horizontalLayout_4.addWidget(self.comboBox_Modele)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.lineEdit_Tour_Poitrine = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Tour_Poitrine.setObjectName("lineEdit_Tour_Poitrine")
        self.gridLayout_2.addWidget(self.lineEdit_Tour_Poitrine, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.lineEdit_Tour_Taille = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Tour_Taille.setObjectName("lineEdit_Tour_Taille")
        self.gridLayout_2.addWidget(self.lineEdit_Tour_Taille, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 3, 0, 1, 1)
        self.lineEdit_Tour_Hanches = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Tour_Hanches.setObjectName("lineEdit_Tour_Hanches")
        self.gridLayout_2.addWidget(self.lineEdit_Tour_Hanches, 3, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 0, 1, 1)
        self.lineEdit_Longueur_Bras = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Longueur_Bras.setObjectName("lineEdit_Longueur_Bras")
        self.gridLayout_2.addWidget(self.lineEdit_Longueur_Bras, 4, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 5, 0, 1, 1)
        self.lineEdit_Largeur_Epaule = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Largeur_Epaule.setObjectName("lineEdit_Largeur_Epaule")
        self.gridLayout_2.addWidget(self.lineEdit_Largeur_Epaule, 5, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_Nouveau = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Nouveau.setObjectName("pushButton_Nouveau")
        self.horizontalLayout.addWidget(self.pushButton_Nouveau)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_Sauvegarder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Sauvegarder.setObjectName("pushButton_Sauvegarder")
        self.horizontalLayout.addWidget(self.pushButton_Sauvegarder)
        spacerItem4 = QtWidgets.QSpacerItem(198, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_Supprimer = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Supprimer.setObjectName("pushButton_Supprimer")
        self.horizontalLayout.addWidget(self.pushButton_Supprimer)
        self.gridLayout_5.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        WorkShop.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WorkShop)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 383, 25))
        self.menubar.setObjectName("menubar")
        self.menu_Fichier = QtWidgets.QMenu(self.menubar)
        self.menu_Fichier.setObjectName("menu_Fichier")
        self.menuConfiguration = QtWidgets.QMenu(self.menubar)
        self.menuConfiguration.setObjectName("menuConfiguration")
        self.menuAide = QtWidgets.QMenu(self.menubar)
        self.menuAide.setObjectName("menuAide")
        WorkShop.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WorkShop)
        self.statusbar.setObjectName("statusbar")
        WorkShop.setStatusBar(self.statusbar)
        self.action_Afficher_liste = QtWidgets.QAction(WorkShop)
        self.action_Afficher_liste.setObjectName("action_Afficher_liste")
        self.action_Enregistrer = QtWidgets.QAction(WorkShop)
        self.action_Enregistrer.setObjectName("action_Enregistrer")
        self.action_Quitter = QtWidgets.QAction(WorkShop)
        self.action_Quitter.setObjectName("action_Quitter")
        self.actionAdministration = QtWidgets.QAction(WorkShop)
        self.actionAdministration.setObjectName("actionAdministration")
        self.actionA_propos_de_WorkShop = QtWidgets.QAction(WorkShop)
        self.actionA_propos_de_WorkShop.setObjectName("actionA_propos_de_WorkShop")
        self.action_Utilisation = QtWidgets.QAction(WorkShop)
        self.action_Utilisation.setObjectName("action_Utilisation")
        self.menu_Fichier.addAction(self.action_Afficher_liste)
        self.menu_Fichier.addAction(self.action_Enregistrer)
        self.menu_Fichier.addSeparator()
        self.menu_Fichier.addAction(self.action_Quitter)
        self.menuConfiguration.addAction(self.actionAdministration)
        self.menuAide.addAction(self.actionA_propos_de_WorkShop)
        self.menuAide.addAction(self.action_Utilisation)
        self.menubar.addAction(self.menu_Fichier.menuAction())
        self.menubar.addAction(self.menuConfiguration.menuAction())
        self.menubar.addAction(self.menuAide.menuAction())

        self.retranslateUi(WorkShop)
        QtCore.QMetaObject.connectSlotsByName(WorkShop)

    def retranslateUi(self, WorkShop):
        _translate = QtCore.QCoreApplication.translate
        WorkShop.setWindowTitle(_translate("WorkShop", "LAGRACE \'S WorkShop"))
        self.groupBox.setTitle(_translate("WorkShop", "Information de Base"))
        self.label_Nom.setText(_translate("WorkShop", "Nom:"))
        self.label_Prenom.setText(_translate("WorkShop", "Prenom:"))
        self.label_Sexe.setText(_translate("WorkShop", "Sexe:"))
        self.radioButton_Masculin.setText(_translate("WorkShop", "M"))
        self.radioButton_Feminin.setText(_translate("WorkShop", "F"))
        self.label_Quartier.setText(_translate("WorkShop", "Quartier:"))
        self.label_Telephone.setText(_translate("WorkShop", "Téléphone:"))
        self.label_Email.setText(_translate("WorkShop", "Email:"))
        self.groupBox_2.setTitle(_translate("WorkShop", "Information Supplementaire"))
        self.label_10.setText(_translate("WorkShop", "Modele:"))
        self.label_11.setText(_translate("WorkShop", "Tour de poitrine:"))
        self.label_13.setText(_translate("WorkShop", "Tour de taille:"))
        self.label_19.setText(_translate("WorkShop", "Tour des hanches:"))
        self.label_15.setText(_translate("WorkShop", "Longueur du bras:"))
        self.label_18.setText(_translate("WorkShop", "Largeur d\'épaule:"))
        self.pushButton_Nouveau.setText(_translate("WorkShop", "&Nouveau"))
        self.pushButton_Sauvegarder.setText(_translate("WorkShop", "&Sauvegarder"))
        self.pushButton_Supprimer.setText(_translate("WorkShop", "&Supprimer"))
        self.menu_Fichier.setTitle(_translate("WorkShop", "&Fichier"))
        self.menuConfiguration.setTitle(_translate("WorkShop", "&Configuration"))
        self.menuAide.setTitle(_translate("WorkShop", "&Aide"))
        self.action_Afficher_liste.setText(_translate("WorkShop", "&Afficher liste"))
        self.action_Enregistrer.setText(_translate("WorkShop", "&Enregistrer"))
        self.action_Quitter.setText(_translate("WorkShop", "&Quitter"))
        self.actionAdministration.setText(_translate("WorkShop", "&Administration"))
        self.actionA_propos_de_WorkShop.setText(_translate("WorkShop", "A propos de &WorkShop"))
        self.action_Utilisation.setText(_translate("WorkShop", "&Utilisation"))

